# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "prank-flashlight-app"

[functions.create-payment-intent]
verify_jwt = false

[functions.health]
verify_jwt = false
